export enum InventoryChangeType {
  IMPORT = 'IMPORT',
  MANUAL_INCREASE = 'MANUAL_INCREASE',
  MANUAL_DECREASE = 'MANUAL_DECREASE',
  ADJUSTMENT = 'ADJUSTMENT',

  ORDER_RESERVED = 'ORDER_RESERVED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
}
