export enum NotificationType {
  ORDER_CREATED = 'ORDER_CREATED',

  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',

  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',

  ORDER_CANCELLED = 'ORDER_CANCELLED',

  REVIEW_APPROVED = 'REVIEW_APPROVED',

  REVIEW_REJECTED = 'REVIEW_REJECTED',
}
